/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CETAH
 */
import java.awt.Color;
import java.awt.Font;
import javax.swing.border.LineBorder;
import javax.swing.JOptionPane;
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();




       
getContentPane().setBackground(new java.awt.Color(204, 255, 255)); 


jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); 
jLabel1.setForeground(new java.awt.Color(0, 102, 204)); 


viewDonor.setBackground(new java.awt.Color(34, 167, 240)); 
manageRequest.setBackground(new java.awt.Color(0, 204, 102)); 
generateReport.setBackground(new java.awt.Color(255, 159, 28)); 
logout.setBackground(new java.awt.Color(255, 0, 0));


viewDonor.setForeground(new java.awt.Color(255, 255, 255));
manageRequest.setForeground(new java.awt.Color(255, 255, 255));
generateReport.setForeground(new java.awt.Color(255, 255, 255));
logout.setForeground(new java.awt.Color(255, 255, 255));


viewDonor.setFont(new java.awt.Font("Arial", 1, 14));
manageRequest.setFont(new java.awt.Font("Arial", 1, 14));
generateReport.setFont(new java.awt.Font("Arial", 1, 14));
logout.setFont(new java.awt.Font("Arial", 1, 14));




    
    sendNotification.setBackground(new Color(0, 153, 76)); 
    sendNotification.setForeground(Color.WHITE);
    sendNotification.setFont(new Font("Segoe UI", Font.BOLD, 14));
 
    
    audiotLogButton.setBackground(new Color(255, 153, 51));       
    audiotLogButton.setForeground(Color.WHITE);
    audiotLogButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
  

  
    manageStaff.setBackground(new Color(51, 153, 255));     
    manageStaff.setForeground(Color.WHITE);
    manageStaff.setFont(new Font("Segoe UI", Font.BOLD, 14));

    viewDonor.setFocusPainted(false);
    manageRequest.setFocusPainted(false);
    generateReport.setFocusPainted(false);
    audiotLogButton.setFocusPainted(false);
    sendNotification.setFocusPainted(false);
    manageStaff.setFocusPainted(false);
    logout.setFocusPainted(false);
  


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        viewDonor = new javax.swing.JButton();
        manageRequest = new javax.swing.JButton();
        generateReport = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        sendNotification = new javax.swing.JButton();
        audiotLogButton = new javax.swing.JButton();
        manageStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Welcome,Boss!");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 40));

        viewDonor.setText("View Donor");
        viewDonor.setPreferredSize(new java.awt.Dimension(150, 40));
        viewDonor.setRolloverEnabled(false);
        viewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorActionPerformed(evt);
            }
        });

        manageRequest.setText("Manage Request");
        manageRequest.setPreferredSize(new java.awt.Dimension(150, 40));
        manageRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestActionPerformed(evt);
            }
        });

        generateReport.setText("Generate Report");
        generateReport.setPreferredSize(new java.awt.Dimension(150, 40));
        generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        sendNotification.setText("Send Notification");
        sendNotification.setPreferredSize(new java.awt.Dimension(150, 40));
        sendNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNotificationActionPerformed(evt);
            }
        });

        audiotLogButton.setText("View Audit Log");
        audiotLogButton.setPreferredSize(new java.awt.Dimension(150, 40));
        audiotLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiotLogButtonActionPerformed(evt);
            }
        });

        manageStaff.setText("Manage Staff");
        manageStaff.setPreferredSize(new java.awt.Dimension(150, 40));
        manageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(audiotLogButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(generateReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(audiotLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(logout)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorActionPerformed
        new ViewDonorsForm().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_viewDonorActionPerformed

    private void manageRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestActionPerformed
       new ManageRequestForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_manageRequestActionPerformed

    private void generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportActionPerformed
       new GenerateReportForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_generateReportActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       new LoginForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void sendNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNotificationActionPerformed
       new SendNotificationForm().setVisible(true);
    }//GEN-LAST:event_sendNotificationActionPerformed

    private void manageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStaffActionPerformed
        JOptionPane.showMessageDialog(this,"Staff Managed Successfully.");
    }//GEN-LAST:event_manageStaffActionPerformed

    private void audiotLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiotLogButtonActionPerformed
        JOptionPane.showMessageDialog(this,"On maintenance.");
    }//GEN-LAST:event_audiotLogButtonActionPerformed

  
    public static void main(String args[]) {
       

  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audiotLogButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton generateReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageRequest;
    private javax.swing.JButton manageStaff;
    private javax.swing.JButton sendNotification;
    private javax.swing.JButton viewDonor;
    // End of variables declaration//GEN-END:variables
}
