/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CETAH
 */
import javax.swing.*;                // For JFrame, JPanel, JTable, JScrollPane, etc.
import javax.swing.table.DefaultTableModel; // To handle table data
import java.awt.*;                   // For layout managers like BorderLayout
import java.io.*;
public class AuditLogForm extends javax.swing.JFrame {

    /**
     * Creates new form AuditLogForm
     */
    public AuditLogForm() {
        initComponents();
        loadAuditLog();
        setLocationRelativeTo(null);
    }
    private void loadAuditLog() {
    try (BufferedReader reader = new BufferedReader(new FileReader("D:\\ceetah\\designProject\\BloodBankSystem\\src\\audit_log.txt"))) {
        txtAuditLog.read(reader, null);
    } catch (IOException e) {
        txtAuditLog.setText("Failed to load audit log.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAuditLog = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboUserFilter = new javax.swing.JComboBox<>();
        labelDate = new javax.swing.JLabel();
        txtDateFilter = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Audit Log Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        txtAuditLog.setColumns(20);
        txtAuditLog.setRows(5);
        jScrollPane1.setViewportView(txtAuditLog);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 470, 390));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel3.setText("Filter by user:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        comboUserFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "User", "Staff" }));
        getContentPane().add(comboUserFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, -1));
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtDateFilter.setText("Date (YYYY-MM-DD):");
        txtDateFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateFilterActionPerformed(evt);
            }
        });
        getContentPane().add(txtDateFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel4.setText("Audit Log");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
               this.dispose(); 
               new AdminDashboard().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtDateFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFilterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       comboUserFilter.setSelectedIndex(0);
    txtDateFilter.setText("");
    loadAuditLog();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        String selectedUser = comboUserFilter.getSelectedItem().toString();
    String dateFilter = txtDateFilter.getText().trim();

    try (BufferedReader reader = new BufferedReader(new FileReader("D:\\ceetah\\designProject\\BloodBankSystem\\src\\audit_log.txt"))) {
        StringBuilder filteredLogs = new StringBuilder();
        String line;
        
        while ((line = reader.readLine()) != null) {
            boolean matchesUser = selectedUser.equals("All") || line.contains(selectedUser);
            boolean matchesDate = dateFilter.isEmpty() || line.contains(dateFilter);

            if (matchesUser && matchesDate) {
                filteredLogs.append(line).append("\n");
            }
        }
        
        txtAuditLog.setText(filteredLogs.toString());
    } catch (IOException e) {
        txtAuditLog.setText("Error loading audit log.");
    }
    }//GEN-LAST:event_btnFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuditLogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboUserFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JTextArea txtAuditLog;
    private javax.swing.JTextField txtDateFilter;
    // End of variables declaration//GEN-END:variables
}
